version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/restaurant-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=05022001
    depends_on:
      - database

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05022001
      POSTGRES_DB: restaurant-management
    ports:
      - "5433:5432"
