# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./Server
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#       - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/restaurant-management
#       - SPRING_DATASOURCE_USERNAME=postgres
#       - SPRING_DATASOURCE_PASSWORD=05022001
#     depends_on:
#       - database

#   frontend:
#     build:
#       context: ./Client
#       dockerfile: Dockerfile
#     ports:
#       - "80:3000"

#   database:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 05022001
#       POSTGRES_DB: restaurant-management
#     ports:
#       - "5433:5432"


# version: '3.8'

services:
  backend:
    container_name: server
    hostname: server
    image: server:latest
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATION_URI=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATION_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_TOKEN_URI=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_TOKEN_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_INFO_URI=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_INFO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_NAME_ATTRIBUTE=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_NAME_ATTRIBUTE}
      - RESTAURANT_MANAGEMENT_APP_JWT_SECRET=${RESTAURANT_MANAGEMENT_APP_JWT_SECRET}
      - RESTAURANT_MANAGEMENT_APP_JWT_EXPIRATION_MS=${RESTAURANT_MANAGEMENT_APP_JWT_EXPIRATION_MS}
      - RESTAURANT_MANAGEMENT_APP_REFRESH_TOKEN_EXPIRED=${RESTAURANT_MANAGEMENT_APP_REFRESH_TOKEN_EXPIRED}
      - SPRINGDOC_SWAGGER_UI_PATH=${SPRINGDOC_SWAGGER_UI_PATH}
      - RESTAURANT_MANAGEMENT_APP_SERVER_URL=${RESTAURANT_MANAGEMENT_APP_SERVER_URL}
      - RESTAURANT_MANAGEMENT_APP_CLIENT_URL=${RESTAURANT_MANAGEMENT_APP_CLIENT_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - VNP_PAY_URL=${VNP_PAY_URL}
      - VNP_RETURN_URL=${VNP_RETURN_URL}
      - VNP_TMN_CODE=${VNP_TMN_CODE}
      - VNP_SECRET_KEY=${VNP_SECRET_KEY}
      - VNP_API_URL=${VNP_API_URL}
      - TIMEOUT=${TIMEOUT}
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY}
      - DISTANCEMATRIX_API_KEY=${DISTANCEMATRIX_API_KEY}
      - RESTAURANT_MANAGEMENT_ADMIN_EMAIL=${RESTAURANT_MANAGEMENT_ADMIN_EMAIL}
      - RESTAURANT_MANAGEMENT_ADMIN_PASSWORD=${RESTAURANT_MANAGEMENT_ADMIN_PASSWORD}
      - RESTAURANT_MANAGEMENT_ADMIN_FULLNAME=${RESTAURANT_MANAGEMENT_ADMIN_FULLNAME}
      - NGROK_DOMAIN_CLIENT=${NGROK_DOMAIN_CLIENT}
      - NGROK_DOMAIN_SERVER=${NGROK_DOMAIN_SERVER}
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    container_name: client
    hostname: client
    image: client:latest
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: database
    hostname: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: